name: Building GSI..

on: push
    
env:
  ROM_URL: https://dl.google.com/dl/android/aosp/walleye-rp1a.201005.004.a1-factory-0c23f6cf.zip
  ROM_NAME: Pixel
  TZ: Europe/London
  MIR: cow
  TYPE: arm32_binder64
  DEVICE: channel
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/00p513-dev/ErfanGSIs-channel.git  ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME $DEVICE --$TYPE
             
       - name: Upload Image
         uses: actions/upload-artifact@v2
         with:
          name: Image
          path: "ErfanGSIs/output/*.img"
          
          
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*.txt
